---
- name: GitHub Actions Runner
  hosts: vagrants
  become: yes
  tasks:
    - name: User for runner service
      user:
        name: '{{ ansible_user }}'
        state: present
    - name: Passwordless sudo for {{ ansible_user }} user
      lineinfile:
        path: /etc/sudoers.d/{{ ansible_user }}
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Setup Docker engine
      include_role:
        name: nickjj.docker
      vars:
        docker__users:
          - '{{ ansible_user }}'
    - name: Setup GitHub actions runner
      include_role:
        name: monolithprojects.github_actions_runner
      vars:
        access_token: "{{ lookup('env','PAT') }}"
        runner_dir: /opt/actions-runner/{{ github_account }}/{{ github_repo }}
        runner_user: vagrant
      tags:
        - uninstall
